In [1]:
import numpy as np   
import pandas as pd
from sklearn import *
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('eduset.csv')

In [3]:
df.head()

Personal_ID_No.        Address Blood_Group AddnlCourses? StudyBlogs?  \
0            97739  426 TONAWANDA          A+     NoCourses  DoNotStudy   
1           101997    39 KOPERNIK          O-   ThreeOrmore  DoNotStudy   
2            50090    214 FLORIDA         AB-     LessThan3  StudyBlogs   
3           192516     42 MATEJKO          B+     NoCourses  StudyBlogs   
4            48081     565 ABBOTT          A-     NoCourses  StudyBlogs   

  WriteRsrchPapers? ListenTechVideos?   CourseCertifications?  \
0  WriteRsrchPapers       DoNotListen  NoCourseCertifications   
1  WriteRsrchPapers       DoNotListen    CourseCertifications   
2     NoRsrchPapers  ListenTechVideos    CourseCertifications   
3  WriteRsrchPapers       DoNotListen    CourseCertifications   
4  WriteRsrchPapers       DoNotListen  NoCourseCertifications   

  IntnlConfattended? PublishedRsrchPapers?    PresentedInConferences?  \
0  AttendedIntnlConf              National  NotPresentedInConferences   
1  AttendedIntnlConf         International     PresentedInConferences   
2  AttendedIntnlConf         International  NotPresentedInConferences   
3       NoIntnlConfs              National     PresentedInConferences   
4  AttendedIntnlConf         International  NotPresentedInConferences   

  WroteTechBlogs? DevelopedTechVideos? Employability?  
0     NoTechBlogs         NoTechVideos            Low  
1     NoTechBlogs         NoTechVideos           Good  
2  WroteTechBlogs         NoTechVideos           Good  
3  WroteTechBlogs  DevelopedTechVideos     Reasonable  
4  WroteTechBlogs  DevelopedTechVideos     Reasonable

In [4]:
df["AddnlCourses?"] = df["AddnlCourses?"].map({'NoCourses':-1,'LessThan3':0,'ThreeOrmore':1})
df["StudyBlogs?"] = df["StudyBlogs?"].map({'StudyBlogs':1,'DoNotStudy':0})
df["WriteRsrchPapers?"] = df["WriteRsrchPapers?"].map({'WriteRsrchPapers':1,'NoRsrchPapers':0})
df["ListenTechVideos?"] = df["ListenTechVideos?"].map({'ListenTechVideos':1,'DoNotListen':0})
df["CourseCertifications?"] = df["CourseCertifications?"].map({'CourseCertifications':1,'NoCourseCertifications':0})
df["IntnlConfattended?"] = df["IntnlConfattended?"].map({'AttendedIntnlConf':1,'NoIntnlConfs':0})
df["PublishedRsrchPapers?"] = df["PublishedRsrchPapers?"].map({'NoRsrchPapers':-1,'National':0,'International':1})
df["PresentedInConferences?"] = df["PresentedInConferences?"].map({'PresentedInConferences':1,'NotPresentedInConferences':0})
df["WroteTechBlogs?"] = df["WroteTechBlogs?"].map({'WroteTechBlogs':1,'NoTechBlogs':0})
df["DevelopedTechVideos?"] = df["DevelopedTechVideos?"].map({'DevelopedTechVideos':1,'NoTechVideos':0})
df["Employability?"] = df["Employability?"].map({'Good':2,'Reasonable':1,'Low':0})
data = df[["AddnlCourses?","StudyBlogs?","WriteRsrchPapers?","ListenTechVideos?","CourseCertifications?","IntnlConfattended?","PublishedRsrchPapers?","PresentedInConferences?","WroteTechBlogs?","DevelopedTechVideos?","Employability?"]].to_numpy()

In [5]:
df.head()

Personal_ID_No.        Address Blood_Group  AddnlCourses?  StudyBlogs?  \
0            97739  426 TONAWANDA          A+             -1            0   
1           101997    39 KOPERNIK          O-              1            0   
2            50090    214 FLORIDA         AB-              0            1   
3           192516     42 MATEJKO          B+             -1            1   
4            48081     565 ABBOTT          A-             -1            1   

   WriteRsrchPapers?  ListenTechVideos?  CourseCertifications?  \
0                  1                  0                      0   
1                  1                  0                      1   
2                  0                  1                      1   
3                  1                  0                      1   
4                  1                  0                      0   

   IntnlConfattended?  PublishedRsrchPapers?  PresentedInConferences?  \
0                   1                      0                        0   
1                   1                      1                        1   
2                   1                      1                        0   
3                   0                      0                        1   
4                   1                      1                        0   

   WroteTechBlogs?  DevelopedTechVideos?  Employability?  
0                0                     0               0  
1                0                     0               2  
2                1                     0               2  
3                1                     1               1  
4                1                     1               1

In [6]:
inputs = data[:,:-1]
outputs = data[:, -1]
training_inputs = inputs[:1000]
training_outputs = outputs[:1000]
testing_inputs = inputs[1000:]
testing_outputs = outputs[1000:]

In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(training_inputs, training_outputs)
predictions = classifier.predict(testing_inputs)
accuracy = accuracy_score(testing_outputs, predictions)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(testing_outputs,predictions))
print(classification_report(testing_outputs,predictions))
print('Accuracy: {:.3f}'.format(accuracy_score(testing_outputs, predictions)))

[[ 389  147    0]
 [ 151 1287  110]
 [   0  170  345]]
              precision    recall  f1-score   support

           0       0.72      0.73      0.72       536
           1       0.80      0.83      0.82      1548
           2       0.76      0.67      0.71       515

    accuracy                           0.78      2599
   macro avg       0.76      0.74      0.75      2599
weighted avg       0.78      0.78      0.78      2599

Accuracy: 0.778
